from Python.admin_addCitizen import *
from Python.admin_addDoc import *
from Python.admin_manageCitizen import *
from Python.admin_manageDoc import *
from Python.admin_downloadAadhaar import *
from Python.admin_downloadPan import *
from Python.admin_downloadDriving import *
from Python.admin_downloadVoter import *
from Python.admin_deleteAadhaar import *
from Python.admin_deletePan import *
from Python.admin_deleteVoter import *
from Python.admin_deleteDriving import *
from Python.admin_deleteCitizen import *
from Python.admin_editCitizen import *
from Python.admin_viewFeedback import *

from Python.citizen_login import *
from Python.citizen_dashboard import *
from Python.citizen_viewDoc import *
from Python.citizen_giveFeedback import *